### ISSUE TITLE
sctool task list command returned-output is truncated

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1321]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: branch-3.1
* **scylla**: 3.1 rc6

### Logs
* test_id: 7d2b56ac-9b39-4bc2-a99d-cba76d6a7ee6
* job log: https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/view/scylla-3.1-test/job/longevity/job/longevity-50gb-4days/16/execution/node/39/log/?consoleFull

### Description

[Description of the bug or feature]

Running the scylla manager repair cli nemesis, it starts a repair and then waits for it to complete with status "Done".
the test fails where a returns task-list output was truncated and missing the running repair id:
```
(DisruptionEvent Severity.ERROR): type=end name=ManagementRepair node=Node longevity-tls-50gb-4d-3-1-db-node-7d2b56ac-6 [52.50.30.74 | 10.0.122.144] (seed: False) duration=17453 error=Encountered an error retrieving sctool table value: repair/356a605c-be64-45a7-bb57-5694617300c0 not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/ec5beed4-8fc8-428d-ba2e-dcb2daae5055', '', '14 Sep 19 06:03:03 UTC (+15s)', 'DONE'], ['healthcheck_rest/ca8e9ba2-d244-4e44-9f23-9b4583642580', '', '14 Sep 19 06:46:48 U']]
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1065, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1274, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 587, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 845, in disrupt_mgmt_repair_cli
    task_final_status = mgr_task.wait_and_get_final_status(timeout=86400)  # timeout is 24 hours
  File "/sct/sdcm/mgmt.py", line 262, in wait_and_get_final_status
    return self.status
  File "/sct/sdcm/mgmt.py", line 169, in status
    str_status = self.get_property(parsed_table=res, column_name='status')
  File "/sct/sdcm/mgmt.py", line 103, in get_property
    return self.sctool.get_table_value(parsed_table=parsed_table, column_name=column_name, identifier=self.id)
  File "/sct/sdcm/mgmt.py", line 832, in get_table_value
    str(parsed_table)))
ScyllaManagerError: Encountered an error retrieving sctool table value: repair/356a605c-be64-45a7-bb57-5694617300c0 not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/ec5beed4-8fc8-428d-ba2e-dcb2daae5055', '', '14 Sep 19 06:03:03 UTC (+15s)', 'DONE'], ['healthcheck_rest/ca8e9ba2-d244-4e44-9f23-9b4583642580', '', '14 Sep 19 06:46:48 U']]
``` 
it uses a retry mechanism in the "wait_for()" function that sometime shows complete check of the specific repair's status and other times fail to find the repair id, getting a truncated result output with only partial data of the cluster tasks.

example output with errors from log:
```
[jenkins@aws-scylla-qa-builder latest]$ grep -i 'wait_for: Retrying Waiting until task' ./sct.log 
...
< t:2019-09-13 08:47:58,661 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 58 ended with: False
< t:2019-09-13 08:50:11,575 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 59 ended with: Encountered an error retrieving sctool table value: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/ec5beed4-8fc8-428d-ba2e-dcb2daae5055', '', '13 Sep 19 08:50:18 UTC (+15s)', 'DONE'], ['healthcheck_rest/ca8e9ba2-d244-4e44-9f23-9b4583642580', '', '13 Sep 19 09']]
< t:2019-09-13 08:52:23,605 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 60 ended with: False
< t:2019-09-13 08:54:33,474 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 61 ended with: False
< t:2019-09-13 08:56:41,538 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 62 ended with: False
< t:2019-09-13 08:58:48,899 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 63 ended with: False
< t:2019-09-13 09:00:50,832 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 64 ended with: False
< t:2019-09-13 09:03:03,766 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 65 ended with: Encountered an error retrieving sctool table value: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/ec5beed4-8fc8-428d-ba2e-dcb2daae5055', '', '13 Sep 19 09:03:03 UTC (+15s)', 'DONE'], ['healthcheck_rest/ca8e9ba2-d244-4e44-9f23-9b4583642580', '', '13 Sep 19 09']]
< t:2019-09-13 09:05:12,897 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 66 ended with: False
< t:2019-09-13 09:07:21,999 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 67 ended with: False
< t:2019-09-13 09:09:35,383 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 68 ended with: False
< t:2019-09-13 09:11:42,890 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 69 ended with: False
< t:2019-09-13 09:13:46,994 f:wait.py         l:48   c:sdcm.wait            p:DEBUG > wait_for: Retrying Waiting until task: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 reaches status of: [<TaskStatus.ERROR: 'ERROR'>, <TaskStatus.STOPPED: 'STOPPED'>, <TaskStatus.DONE: 'DONE'>]: attempt 70 ended with: Encountered an error retrieving sctool table value: repair/5e300ad1-ae6f-4180-93c0-e20153e75497 not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/ec5beed4-8fc8-428d-ba2e-dcb2daae5055', '', '13 Sep 19 09:13:48 UTC (+15s)', 'DONE'], ['healthcheck_rest/ca8e9ba2-d244-4e44-9f23-9b4583642580', '', '13 Sep 19 09']]
```
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by ShlomiBalalis** [comment]
I haven't seen this issue reproduced in a WHILE. closing
