### ISSUE TITLE
Manager repair cli nemesis fails: repair task not found in task list

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-cluster-tests#1382]
### Prerequisites

* [x] Are you rebased to master ?
* [x] Is it reproducible ?
* [ ] Did you perform a cursory search if this issue isn't opened ?

### Versions
* **SCT**: 3.1
* **scylla**: [branch or commit hash]

### Logs
* test_id: 5467dbcb-af83-4fd1-94f2-4925d7429a28
* job log: [e.x. https://cloudius-jenkins-test.s3.amazonaws.com/5a2c3b72-40f8-4992-8b5a-5c4aec8bf0c6/job-2019-05-14T09.59-c85338a.zip]

### Description
happened in 50gb 3.1 longevity on manager repair cli nemesis.
after repair task finishes successfully, the test fails when the repair task is missing from parsed task list, then in logs we see the missing repair task details only later on, after results already returned to the caller function.
test failure is:
```
(DisruptionEvent Severity.ERROR): type=end name=ManagementRepair node=Node longevity-tls-50gb-4d-3-1-db-node-5467dbcb-10 [34.244.104.65 | 10.0.105.249] (seed: False) duration=34628 error=Encountered an error retrieving sctool table value: repair/c31c34f1-5f4a-417d-8c06-b8837467d03f not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/73f9eb7d-2b96-47b0-b59e-2c7d6e76bfab', '', '08 Oct 19 02:30:58 UTC (+15s)', 'RUNNING'], ['healthcheck_rest/97673ee2-754c-4bfe-bae6-ff16274c8a5b', '', '08 Oct 19 02']]
Traceback (most recent call last):
  File "/sct/sdcm/nemesis.py", line 1067, in wrapper
    result = method(*args, **kwargs)
  File "/sct/sdcm/nemesis.py", line 1276, in disrupt
    self.call_random_disrupt_method()
  File "/sct/sdcm/nemesis.py", line 588, in call_random_disrupt_method
    disrupt_method()
  File "/sct/sdcm/nemesis.py", line 846, in disrupt_mgmt_repair_cli
    task_final_status = mgr_task.wait_and_get_final_status(timeout=86400)  # timeout is 24 hours
  File "/sct/sdcm/mgmt.py", line 262, in wait_and_get_final_status
    return self.status
  File "/sct/sdcm/mgmt.py", line 169, in status
    str_status = self.get_property(parsed_table=res, column_name='status')
  File "/sct/sdcm/mgmt.py", line 103, in get_property
    return self.sctool.get_table_value(parsed_table=parsed_table, column_name=column_name, identifier=self.id)
  File "/sct/sdcm/mgmt.py", line 832, in get_table_value
    str(parsed_table)))
ScyllaManagerError: Encountered an error retrieving sctool table value: repair/c31c34f1-5f4a-417d-8c06-b8837467d03f not found in: [['task', 'arguments', 'next run', 'status'], ['healthcheck/73f9eb7d-2b96-47b0-b59e-2c7d6e76bfab', '', '08 Oct 19 02:30:58 UTC (+15s)', 'RUNNING'], ['healthcheck_rest/97673ee2-754c-4bfe-bae6-ff16274c8a5b', '', '08 Oct 19 02']]
```
after first analysis, we agreed to add more prints in a private branch to see if the problem is in the remote side or table parsing side. 
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
