### ISSUE TITLE
Add more linting rules to ruff

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-cluster-tests#7860]
A tab of the rules/set we want to activate 

### Tasks
- [ ] https://docs.astral.sh/ruff/rules/#isort-i - worth doing, it would align things, and can avoid some merge conflicts
- [ ] https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz - this can help avoid lot's of time offset issues, and also future proof, like some api being depreciated - we have 147 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth - we have 830 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-logging-log - make sure we have proper name for out loggers, we have 4 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-unused-arguments-arg - we have 321 issue with that
- [x] https://docs.astral.sh/ruff/rules/undefined-name/ - F821
- [x] https://docs.astral.sh/ruff/rules/undefined-local/ - F823
- [x] https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/#f-string-missing-placeholders-f541
- [ ] https://docs.astral.sh/ruff/rules/private-member-access/#private-member-access-slf001 - we have lots of those, not sure how critical it would be to fix or ignore those
- [ ] https://docs.astral.sh/ruff/rules/missing-f-string-syntax/ - we have 2 of those
- [ ] https://docs.astral.sh/ruff/rules/explicit-f-string-type-conversion/ - we have 45 of those
- [ ] https://docs.astral.sh/ruff/rules/implicit-optional/ - we have 284 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-builtins-a -  we have 7 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-logging-log - we have 4 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-logging-format-g - we have 430 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-pie-pie - we have 62 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-print-t20 - we have 167 of those
- [ ] https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt - we have ~1500 of those
