### ISSUE TITLE
Add 90% storage utilization tests

### ISSUE THREAD

**Issue by pehala** [scylladb/scylla-cluster-tests#9129]
# Overview
Add both test & testcases to verify that Scylla can run with 90% storage utilization with tablets

# Test Requirements
### Workload
* If not specified otherwise, all workloads are assumed to be 50% reads / 50% writes.

### Latency
* Operation latency measured with 50% of the max Throughput.
* P99 should be under 10ms while scaling both, for read and write

### Storage utilization
* Maximum storage utilization before a scale out: 90%
* Minimum storage utilization before a scale in: 75%.
   * Make sure that after scale in we will be below maximum storage utilization

### Scale Time (Duration):
* Base on 100MB/s BW per core
* Scaling up operation require 2.5 extra minutes for node boot time
* Validating scale time in the worst case

# Tasks

- [x] #9130
- [x] run-longevity-tests, run-nemesis-at-90-percent: #9155

### Scaling
- [ ] 3node-scale-out-scale-in: #9156
- [ ] multidc-cluster-scaleout: #9157

### Data deletion
- [x] data-removal-drop-compaction: #9166
- [x] data-removal-truncate-compaction: #9169
- [x] data-removal-ttl-compaction #9167

### Scaling time
- [x] time-to-double-cluster: #9220

### Mixed instances
- [x] add-larger-instance: #9257
- [x] add-small-instance: #9256

### Extras
- [x] multiple-small-tables: #9309
- [ ] change-instance-type: 
- [ ] double-cluster-smaller-instances: #9597

**Comment by mykaul** [comment]
@pehala - we are missing (or I could not find) mixed nodes support - we add a different instance type, same family to the cluster - say you had several i4i.8xlarge, now you add an additional i4i.2xlarge. This will happen often.
CC @swasik

**Comment by pehala** [comment]
> [@pehala](https://github.com/pehala) - we are missing (or I could not find) mixed nodes support - we add a different instance type, same family to the cluster - say you had several i4i.8xlarge, now you add an additional i4i.2xlarge. This will happen often.
> CC [@swasik](https://github.com/swasik)

We have https://github.com/scylladb/scylla-cluster-tests/issues/9257 (3 L -> +XL) and https://github.com/scylladb/scylla-cluster-tests/issues/9256 (3 XL -> +L), which add different instance sizes to the cluster, does that cover the mixed node use?

**Comment by Lakshmipathi** [comment]
<details><summary>Results</summary>

 [Argus] (https://argus.scylladb.com/tests/scylla-cluster-tests/0c0af1c9-d798-48d1-bfaa-04767ef08d38)

### Configuration:
- 3 x i4i.2xlarge - 1.875TB Disk in each node
- Raw Data set size: 1.16TB (RF =3)

### Workload during latency measurements: 

- c-s mixed (R/W 50/50)
- 1KB Row size (8 columns, 128 bytes each)
- Gauss Distribution - writing and reading only part of the dataset.
> cassandra-stress mixed no-warmup cl=QUORUM duration=800m -schema keyspace=ks_mixed1 'replication(strategy=NetworkTopologyStrategy,replication_factor=3)' -mode cql3 native -rate 'threads=300 fixed=16875/s' -col 'size=FIXED(128) n=FIXED(8)' -pop 'dist=gauss(1..650000000,325000000,6500000)'

Disk Usage
![Image](https://github.com/user-attachments/assets/38ff6f64-401f-4746-b142-1f32536e5c97)


Load
![Image](https://github.com/user-attachments/assets/a8b3db6d-331b-4e61-849b-fcae91f4c371)

Latency 
p99 read and write shows improvement while throughput remains stable.

![Image](https://github.com/user-attachments/assets/aca47c77-11fb-47c2-889b-7bd3196a7a14)
